version: "3.9"
services:
  main-db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hnews
    ports:
      - "5455:5432"
